[2017-11-06 09:16:25] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI)" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:16:25] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:16:25] php.CRITICAL: Uncaught Exception: An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43, Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:16:25] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI)" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43, Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:16:25] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:34:30] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI)" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:34:30] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:34:30] php.CRITICAL: Uncaught Exception: An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43, Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:34:30] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI)" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43, Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:34:30] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:40:15] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI)" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:40:15] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:40:15] php.CRITICAL: Uncaught Exception: An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43, Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:40:15] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI)" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43, Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:40:15] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:41:37] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI)" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:41:37] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:41:37] php.CRITICAL: Uncaught Exception: An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43, Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:41:37] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI)" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43, Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:41:37] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 103) {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Accès refusé pour l'utilisateur: 'root'@'@localhost' (mot de passe: OUI) at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:43)"} []
[2017-11-06 09:42:02] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:42:03] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:42:03] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:42:03] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53) {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:42:03] php.CRITICAL: Uncaught Exception: An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105, Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:42:03] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105, Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:42:03] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:42:03] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53) {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:37] console.ERROR: Error thrown while running command ""doctrine:database:" update --force". Message: "Command "doctrine:database:" is ambiguous. Did you mean one of these?     doctrine:database:create Creates the configured database     doctrine:database:drop   Drops the configured database     doctrine:database:import Import SQL file(s) directly to Database." {"error":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"doctrine:database:\" is ambiguous.\nDid you mean one of these?\n    doctrine:database:create Creates the configured database\n    doctrine:database:drop   Drops the configured database\n    doctrine:database:import Import SQL file(s) directly to Database. at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Application.php:612)","command":"\"doctrine:database:\" update --force","message":"Command \"doctrine:database:\" is ambiguous.\nDid you mean one of these?\n    doctrine:database:create Creates the configured database\n    doctrine:database:drop   Drops the configured database\n    doctrine:database:import Import SQL file(s) directly to Database."} []
[2017-11-06 09:51:45] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:51:45] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:45] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:51:45] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53) {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:45] php.CRITICAL: Uncaught Exception: An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105, Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:45] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105, Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:45] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:51:45] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53) {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:47] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:51:47] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:47] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:51:47] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53) {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:47] php.CRITICAL: Uncaught Exception: An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105, Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:47] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105, Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:47] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:51:47] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53) {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:49] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:51:49] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:49] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:51:49] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53) {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:49] php.CRITICAL: Uncaught Exception: An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105, Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:49] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas" at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105, Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:51:49] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:51:49] request.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:  SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\wamp64\www\ProjetSymfony\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 53) {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1' with params [1]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 La table 'symfony.cms_template' n'existe pas at C:\\wamp64\\www\\ProjetSymfony\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-11-06 09:52:03] console.ERROR: Error thrown while running command ""doctrine:database:update" --force". Message: "Command "doctrine:database:update" is not defined.  Did you mean one of these?     doctrine:database:create     doctrine:database:drop     doctrine:database:import     doctrine:schema:update" {"error":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"doctrine:database:update\" is not defined.\n\nDid you mean one of these?\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:database:import\n    doctrine:schema:update at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Application.php:584)","command":"\"doctrine:database:update\" --force","message":"Command \"doctrine:database:update\" is not defined.\n\nDid you mean one of these?\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:database:import\n    doctrine:schema:update"} []
[2017-11-06 09:52:21] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2017-11-06 09:52:22] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2017-11-06 09:52:22] doctrine.DEBUG: CREATE TABLE cms_ext_translations (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(8) NOT NULL, object_class VARCHAR(255) NOT NULL, field VARCHAR(32) NOT NULL, foreign_key VARCHAR(64) NOT NULL, content LONGTEXT DEFAULT NULL, INDEX translations_lookup_idx (locale, object_class, foreign_key), UNIQUE INDEX lookup_unique_idx (locale, object_class, field, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-06 09:52:23] doctrine.DEBUG: CREATE TABLE cms_ext_log_entries (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', username VARCHAR(255) DEFAULT NULL, INDEX log_class_lookup_idx (object_class), INDEX log_date_lookup_idx (logged_at), INDEX log_user_lookup_idx (username), INDEX log_version_lookup_idx (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-06 09:52:24] doctrine.DEBUG: CREATE TABLE cms_template (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-06 09:52:24] doctrine.DEBUG: CREATE TABLE cms_configuration (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, value LONGTEXT DEFAULT NULL, date_add DATETIME NOT NULL, date_upd DATETIME NOT NULL, UNIQUE INDEX UNIQ_15B31E025E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-06 09:52:24] doctrine.DEBUG: CREATE TABLE cms_module (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, version VARCHAR(15) NOT NULL, UNIQUE INDEX UNIQ_3ED239505E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-06 09:52:25] doctrine.DEBUG: CREATE TABLE cms_hook (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, title VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_63CEEE285E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-06 09:52:25] doctrine.DEBUG: CREATE TABLE cms_hook_module (id INT AUTO_INCREMENT NOT NULL, id_module INT NOT NULL, id_hook INT NOT NULL, position INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-06 09:52:26] doctrine.DEBUG: CREATE TABLE cms_article (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, cover VARCHAR(255) NOT NULL, text LONGTEXT NOT NULL, slug VARCHAR(255) NOT NULL, category_id INT NOT NULL, created_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_5CD60177989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-06 09:52:26] doctrine.DEBUG: CREATE TABLE cms_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, parent_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_6CA2D53C989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-06 09:52:26] doctrine.DEBUG: CREATE TABLE cms_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', UNIQUE INDEX UNIQ_4A057B3492FC23A8 (username_canonical), UNIQUE INDEX UNIQ_4A057B34A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_4A057B34C05FB297 (confirmation_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB [] []
[2017-11-06 09:52:31] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:52:31] php.CRITICAL: Call to a member function getName() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:30)"} []
[2017-11-06 09:52:31] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getName() on null" at C:\wamp64\www\ProjetSymfony\src\TemplateBundle\Service\TemplateManager.php line 30 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:30)"} []
[2017-11-06 09:52:31] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Syntax: Unknown "abbr_class" filter. at C:\wamp64\www\ProjetSymfony\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Resources\views\Exception\exception.html.twig line 6) {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"abbr_class\" filter. at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle\\Resources\\views\\Exception\\exception.html.twig:6)"} []
[2017-11-06 09:54:18] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:54:18] php.CRITICAL: Call to a member function getName() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:30)"} []
[2017-11-06 09:54:18] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getName() on null" at C:\wamp64\www\ProjetSymfony\src\TemplateBundle\Service\TemplateManager.php line 30 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:30)"} []
[2017-11-06 09:54:18] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Syntax: Unknown "abbr_class" filter. at C:\wamp64\www\ProjetSymfony\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Resources\views\Exception\exception.html.twig line 6) {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"abbr_class\" filter. at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle\\Resources\\views\\Exception\\exception.html.twig:6)"} []
[2017-11-06 09:54:49] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:54:49] php.CRITICAL: Call to a member function getName() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:30)"} []
[2017-11-06 09:54:49] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getName() on null" at C:\wamp64\www\ProjetSymfony\src\TemplateBundle\Service\TemplateManager.php line 30 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:30)"} []
[2017-11-06 09:54:49] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Syntax: Unknown "abbr_class" filter. at C:\wamp64\www\ProjetSymfony\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Resources\views\Exception\exception.html.twig line 6) {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"abbr_class\" filter. at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle\\Resources\\views\\Exception\\exception.html.twig:6)"} []
[2017-11-06 09:59:06] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 09:59:06] php.CRITICAL: Call to a member function getName() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:30)"} []
[2017-11-06 09:59:06] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getName() on null" at C:\wamp64\www\ProjetSymfony\src\TemplateBundle\Service\TemplateManager.php line 30 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:30)"} []
[2017-11-06 09:59:06] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Syntax: Unknown "abbr_class" filter. at C:\wamp64\www\ProjetSymfony\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Resources\views\Exception\exception.html.twig line 6) {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"abbr_class\" filter. at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle\\Resources\\views\\Exception\\exception.html.twig:6)"} []
[2017-11-06 10:09:30] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 10:09:30] php.CRITICAL: Call to a member function getName() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:29)"} []
[2017-11-06 10:09:30] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getName() on null" at C:\wamp64\www\ProjetSymfony\src\TemplateBundle\Service\TemplateManager.php line 29 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:29)"} []
[2017-11-06 10:09:30] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Syntax: Unknown "abbr_class" filter. at C:\wamp64\www\ProjetSymfony\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Resources\views\Exception\exception.html.twig line 6) {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"abbr_class\" filter. at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle\\Resources\\views\\Exception\\exception.html.twig:6)"} []
[2017-11-06 10:09:36] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 10:09:36] php.CRITICAL: Call to a member function getName() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:29)"} []
[2017-11-06 10:09:36] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getName() on null" at C:\wamp64\www\ProjetSymfony\src\TemplateBundle\Service\TemplateManager.php line 29 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:29)"} []
[2017-11-06 10:09:36] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Syntax: Unknown "abbr_class" filter. at C:\wamp64\www\ProjetSymfony\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Resources\views\Exception\exception.html.twig line 6) {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"abbr_class\" filter. at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle\\Resources\\views\\Exception\\exception.html.twig:6)"} []
[2017-11-06 10:10:27] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 10:10:27] php.CRITICAL: Call to a member function getName() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:25)"} []
[2017-11-06 10:10:27] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getName() on null" at C:\wamp64\www\ProjetSymfony\src\TemplateBundle\Service\TemplateManager.php line 25 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:25)"} []
[2017-11-06 10:10:27] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Syntax: Unknown "abbr_class" filter. at C:\wamp64\www\ProjetSymfony\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Resources\views\Exception\exception.html.twig line 6) {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"abbr_class\" filter. at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle\\Resources\\views\\Exception\\exception.html.twig:6)"} []
[2017-11-06 10:10:28] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 10:10:28] php.CRITICAL: Call to a member function getName() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:25)"} []
[2017-11-06 10:10:28] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getName() on null" at C:\wamp64\www\ProjetSymfony\src\TemplateBundle\Service\TemplateManager.php line 25 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:25)"} []
[2017-11-06 10:10:28] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Syntax: Unknown "abbr_class" filter. at C:\wamp64\www\ProjetSymfony\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Resources\views\Exception\exception.html.twig line 6) {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"abbr_class\" filter. at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle\\Resources\\views\\Exception\\exception.html.twig:6)"} []
[2017-11-06 10:10:29] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 10:10:29] php.CRITICAL: Call to a member function getName() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:25)"} []
[2017-11-06 10:10:29] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getName() on null" at C:\wamp64\www\ProjetSymfony\src\TemplateBundle\Service\TemplateManager.php line 25 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:25)"} []
[2017-11-06 10:10:29] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Syntax: Unknown "abbr_class" filter. at C:\wamp64\www\ProjetSymfony\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Resources\views\Exception\exception.html.twig line 6) {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"abbr_class\" filter. at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle\\Resources\\views\\Exception\\exception.html.twig:6)"} []
[2017-11-06 10:13:23] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 10:13:23] php.CRITICAL: Call to a member function getName() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:30)"} []
[2017-11-06 10:13:23] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getName() on null" at C:\wamp64\www\ProjetSymfony\src\TemplateBundle\Service\TemplateManager.php line 30 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:30)"} []
[2017-11-06 10:13:24] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Syntax: Unknown "abbr_class" filter. at C:\wamp64\www\ProjetSymfony\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Resources\views\Exception\exception.html.twig line 6) {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"abbr_class\" filter. at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle\\Resources\\views\\Exception\\exception.html.twig:6)"} []
[2017-11-06 10:13:24] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 10:13:24] php.CRITICAL: Call to a member function getName() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:30)"} []
[2017-11-06 10:13:24] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getName() on null" at C:\wamp64\www\ProjetSymfony\src\TemplateBundle\Service\TemplateManager.php line 30 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getName() on null at C:\\wamp64\\www\\ProjetSymfony\\src\\TemplateBundle\\Service\\TemplateManager.php:30)"} []
[2017-11-06 10:13:24] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Syntax: Unknown "abbr_class" filter. at C:\wamp64\www\ProjetSymfony\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Resources\views\Exception\exception.html.twig line 6) {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"abbr_class\" filter. at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle\\Resources\\views\\Exception\\exception.html.twig:6)"} []
[2017-11-06 10:13:37] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.is_active AS is_active_3 FROM cms_template t0 WHERE t0.is_active = ? LIMIT 1 [true] []
[2017-11-06 10:13:37] php.CRITICAL: Type error: Argument 1 passed to HookBundle\Twig\HookExtension::__construct() must be an instance of Doctrine\ORM\EntityManager, instance of ModuleBundle\Service\ModuleManager given, called in C:\wamp64\www\ProjetSymfony\var\cache\dev\appDevDebugProjectContainer.php on line 2100 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to HookBundle\\Twig\\HookExtension::__construct() must be an instance of Doctrine\\ORM\\EntityManager, instance of ModuleBundle\\Service\\ModuleManager given, called in C:\\wamp64\\www\\ProjetSymfony\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2100 at C:\\wamp64\\www\\ProjetSymfony\\src\\HookBundle\\Twig\\HookExtension.php:17)"} []
[2017-11-06 10:13:37] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to HookBundle\Twig\HookExtension::__construct() must be an instance of Doctrine\ORM\EntityManager, instance of ModuleBundle\Service\ModuleManager given, called in C:\wamp64\www\ProjetSymfony\var\cache\dev\appDevDebugProjectContainer.php on line 2100" at C:\wamp64\www\ProjetSymfony\src\HookBundle\Twig\HookExtension.php line 17 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to HookBundle\\Twig\\HookExtension::__construct() must be an instance of Doctrine\\ORM\\EntityManager, instance of ModuleBundle\\Service\\ModuleManager given, called in C:\\wamp64\\www\\ProjetSymfony\\var\\cache\\dev\\appDevDebugProjectContainer.php on line 2100 at C:\\wamp64\\www\\ProjetSymfony\\src\\HookBundle\\Twig\\HookExtension.php:17)"} []
[2017-11-06 10:13:37] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Syntax: Unknown "abbr_class" filter. at C:\wamp64\www\ProjetSymfony\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Resources\views\Exception\exception.html.twig line 6) {"exception":"[object] (Twig_Error_Syntax(code: 0): Unknown \"abbr_class\" filter. at C:\\wamp64\\www\\ProjetSymfony\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\TwigBundle\\Resources\\views\\Exception\\exception.html.twig:6)"} []
